### ISSUE TITLE
Implement true access modifiers

### ISSUE THREAD

**Issue by KevinTyrrell** [kurapica/PLoop#10]
Implement the access modifiers `private`, `protected`, and `public`. This would replace all your identifiers such as `__private_variable`.

`private` can be implemented using closures:
```lua
function get_x = (function()
    local x = -- Variable x is protected by a closure
    return function()
        return x
    end
end)()
```

Without access modifiers, you can't have true objects.

**Comment by kurapica** [comment]
For dynamic languages, it's better to keep the real property value in itself, like Python. So, for the current version, there is several ways to gain the private variables:

I. Using the closure:

``` lua
require "PLoop"(function(_ENV)
    class "Person" (function(_ENV)
        -- Fake method, a false safe
        function SetName() end
        function GetName() end

        property "Name" { set = "SetName", get = "GetName" }

        function __ctor(self, name)
            self.SetName = function(self, val) name = val end
            self.GetName = function(self) return name end
        end
    end)

    p = Person("Ann")
    print(p.Name)  -- Ann

    class "Student" (function(_ENV)
        inherit "Person"

        function GetName(self)
            print("This method can't be accessed")
            return super.GetName(self)
        end
    end)

    p = Student("Ben")
    print(p.Name)
end)
```

If we use the closure, we must give the method to the object during construction, it'd works for single classes, but bad for the inheritance, given the method to object directly will ruin the whole method inheritance system. 

So it's not usable for private variables(But the closures are largely used by the PLoop to reduce the if-branch determination in struct validation, object construction, argument checking and etc, decrease the cost more than 50%)

II. Besides the closures, there is a way to declared the private variables for the objects without ruining the system:

```
require "PLoop"(function(_ENV)
    class "Person" (function(_ENV)
        local _PrivateName = setmetatable({}, { __mode = "k" })

        property "Name" {
            set = function(self, name) _PrivateName[self] = name end,
            get = function(self) return _PrivateName[self] end,
        }
    end)

    p = Person{ Name = "Ann" }
    print(p.Name, next(p)) -- Ann   nil
end)
```

It'd works very well for the most part, but it's a disaster for the multi OS thread platform like the Openresty.

If we keep the variables in the object, for two objects in different os thread, object A want write its name, the other object B want read its name, when A write to the _PrivateName, it'd cause the table to refresh its hash, so B could be failed to read its name at the same time.

To solve it, we should add a lock before read/write to the _PrivateName, but the lock will largely reduce the system performance. 

So that's why the dynamic languages like Python will keep the variables in the object as default. I also can't choose the private variables as the default mechanism for the lib's common features.

If you keep using the lib in single os thread platform, you can try the share table trick. We also can define an attribute to simple the job:

```lua
require "PLoop"(function(_ENV)
    class "__Private__" (function(_ENV)
        extend "IInitAttribute"

        local meta = { __mode = "k" }

        function InitDefinition(self, target, targettype, definition, owner, name, stack)
            local cache     = setmetatable({}, meta)
            definition.set  = function(self, val) cache[self] = val end
            definition.get  = function(self) return cache[self] end
        end

        property "AttributeTarget"  { type = AttributeTargets,  default = AttributeTargets.Property }
    end)

    class "Person" (function(_ENV)
        __Private__() property "Name" { type = String, default = "Anonymous" }
        __Private__() property "Age" { type = Number, default = 0 }
    end)

    p = Person()
    print(p.Name, p.Age) -- Anonymous  0

    p.Name = "Ann"
    p.Age = 22
    print(p.Name, p.Age, next(p)) -- Ann 22  nil
end)
```
